version: '3'

services:
  envoy:
    build:
      context: ./envoy
    ports:
      - '8080:8080'
      - '9901:9901'
    networks:
      - server-net
  server:
    build:
      context: ./server
    volumes:
      - ./server/src:/go/src/github.com/dirkarnez/grpc-web-starter/server
    ports:
      - '9090:9090'
    networks:
      - server-net

networks:
  server-net: